name: doodo_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_slidable: ^3.0.1
  http: ^1.1.0
  page_transition: ^2.1.0
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logoDoodo.jpg
    - lib/assets/images/doodo_logo_rock.jpeg
