class Country {
  final String name;
  final String code;
  final String flagPath;

  Country({required this.name, required this.code, required this.flagPath});
}

class CountryList {
  static List<Country> get countries => [
        Country(
            name: "Afghanistan", code: "AF", flagPath: "assets/flags/af.png"),
        Country(name: "Albania", code: "AL", flagPath: "assets/flags/al.png"),
        Country(name: "Algeria", code: "DZ", flagPath: "assets/flags/dz.png"),
        Country(name: "Andorra", code: "AD", flagPath: "assets/flags/ad.png"),
        Country(name: "Angola", code: "AO", flagPath: "assets/flags/ao.png"),
        Country(
            name: "Antigua and Barbuda",
            code: "AG",
            flagPath: "assets/flags/ag.png"),
        Country(name: "Argentina", code: "AR", flagPath: "assets/flags/ar.png"),
        Country(name: "Armenia", code: "AM", flagPath: "assets/flags/am.png"),
        Country(name: "Australia", code: "AU", flagPath: "assets/flags/au.png"),
        Country(name: "Austria", code: "AT", flagPath: "assets/flags/at.png"),
        Country(
            name: "Azerbaijan", code: "AZ", flagPath: "assets/flags/az.png"),
        Country(name: "Bahamas", code: "BS", flagPath: "assets/flags/bs.png"),
        Country(name: "Bahrain", code: "BH", flagPath: "assets/flags/bh.png"),
        Country(
            name: "Bangladesh", code: "BD", flagPath: "assets/flags/bd.png"),
        Country(name: "Barbados", code: "BB", flagPath: "assets/flags/bb.png"),
        Country(name: "Belarus", code: "BY", flagPath: "assets/flags/by.png"),
        Country(name: "Belgium", code: "BE", flagPath: "assets/flags/be.png"),
        Country(name: "Belize", code: "BZ", flagPath: "assets/flags/bz.png"),
        Country(name: "Benin", code: "BJ", flagPath: "assets/flags/bj.png"),
        Country(name: "Bhutan", code: "BT", flagPath: "assets/flags/bt.png"),
        Country(name: "Bolivia", code: "BO", flagPath: "assets/flags/bo.png"),
        Country(
            name: "Bosnia and Herzegovina",
            code: "BA",
            flagPath: "assets/flags/ba.png"),
        Country(name: "Botswana", code: "BW", flagPath: "assets/flags/bw.png"),
        Country(name: "Brazil", code: "BR", flagPath: "assets/flags/br.png"),
        Country(name: "Brunei", code: "BN", flagPath: "assets/flags/bn.png"),
        Country(name: "Bulgaria", code: "BG", flagPath: "assets/flags/bg.png"),
        Country(
            name: "Burkina Faso", code: "BF", flagPath: "assets/flags/bf.png"),
        Country(name: "Burundi", code: "BI", flagPath: "assets/flags/bi.png"),
        Country(
            name: "Cabo Verde", code: "CV", flagPath: "assets/flags/cv.png"),
        Country(name: "Cambodia", code: "KH", flagPath: "assets/flags/kh.png"),
        Country(name: "Cameroon", code: "CM", flagPath: "assets/flags/cm.png"),
        Country(name: "Canada", code: "CA", flagPath: "assets/flags/ca.png"),
        Country(
            name: "Central African Republic",
            code: "CF",
            flagPath: "assets/flags/cf.png"),
        Country(name: "Chad", code: "TD", flagPath: "assets/flags/td.png"),
        Country(name: "Chile", code: "CL", flagPath: "assets/flags/cl.png"),
        Country(name: "China", code: "CN", flagPath: "assets/flags/cn.png"),
        Country(name: "Colombia", code: "CO", flagPath: "assets/flags/co.png"),
        Country(name: "Comoros", code: "KM", flagPath: "assets/flags/km.png"),
        Country(name: "Congo", code: "CG", flagPath: "assets/flags/cg.png"),
        Country(
            name: "Costa Rica", code: "CR", flagPath: "assets/flags/cr.png"),
        Country(name: "Croatia", code: "HR", flagPath: "assets/flags/hr.png"),
        Country(name: "Cuba", code: "CU", flagPath: "assets/flags/cu.png"),
        Country(name: "Cyprus", code: "CY", flagPath: "assets/flags/cy.png"),
        Country(
            name: "Czech Republic",
            code: "CZ",
            flagPath: "assets/flags/cz.png"),
        Country(name: "Denmark", code: "DK", flagPath: "assets/flags/dk.png"),
        Country(name: "Djibouti", code: "DJ", flagPath: "assets/flags/dj.png"),
        Country(name: "Dominica", code: "DM", flagPath: "assets/flags/dm.png"),
        Country(
            name: "Dominican Republic",
            code: "DO",
            flagPath: "assets/flags/do.png"),
        Country(
            name: "East Timor", code: "TL", flagPath: "assets/flags/tl.png"),
        Country(name: "Ecuador", code: "EC", flagPath: "assets/flags/ec.png"),
        Country(name: "Egypt", code: "EG", flagPath: "assets/flags/eg.png"),
        Country(
            name: "El Salvador", code: "SV", flagPath: "assets/flags/sv.png"),
        Country(
            name: "Equatorial Guinea",
            code: "GQ",
            flagPath: "assets/flags/gq.png"),
        Country(name: "Eritrea", code: "ER", flagPath: "assets/flags/er.png"),
        Country(name: "Estonia", code: "EE", flagPath: "assets/flags/ee.png"),
        Country(name: "Eswatini", code: "SZ", flagPath: "assets/flags/sz.png"),
        Country(name: "Ethiopia", code: "ET", flagPath: "assets/flags/et.png"),
        Country(name: "Fiji", code: "FJ", flagPath: "assets/flags/fj.png"),
        Country(name: "Finland", code: "FI", flagPath: "assets/flags/fi.png"),
        Country(name: "France", code: "FR", flagPath: "assets/flags/fr.png"),
        Country(name: "Gabon", code: "GA", flagPath: "assets/flags/ga.png"),
        Country(name: "Gambia", code: "GM", flagPath: "assets/flags/gm.png"),
        Country(name: "Georgia", code: "GE", flagPath: "assets/flags/ge.png"),
        Country(name: "Germany", code: "DE", flagPath: "assets/flags/de.png"),
        Country(name: "Ghana", code: "GH", flagPath: "assets/flags/gh.png"),
        Country(name: "Greece", code: "GR", flagPath: "assets/flags/gr.png"),
        Country(name: "Grenada", code: "GD", flagPath: "assets/flags/gd.png"),
        Country(name: "Guatemala", code: "GT", flagPath: "assets/flags/gt.png"),
        Country(name: "Guinea", code: "GN", flagPath: "assets/flags/gn.png"),
        Country(
            name: "Guinea-Bissau", code: "GW", flagPath: "assets/flags/gw.png"),
        Country(name: "Guyana", code: "GY", flagPath: "assets/flags/gy.png"),
        Country(name: "Haiti", code: "HT", flagPath: "assets/flags/ht.png"),
        Country(name: "Honduras", code: "HN", flagPath: "assets/flags/hn.png"),
        Country(name: "Hungary", code: "HU", flagPath: "assets/flags/hu.png"),
        Country(name: "Iceland", code: "IS", flagPath: "assets/flags/is.png"),
        Country(name: "India", code: "IN", flagPath: "assets/flags/in.png"),
        Country(name: "Indonesia", code: "ID", flagPath: "assets/flags/id.png"),
        Country(name: "Iran", code: "IR", flagPath: "assets/flags/ir.png"),
        Country(name: "Iraq", code: "IQ", flagPath: "assets/flags/iq.png"),
        Country(name: "Ireland", code: "IE", flagPath: "assets/flags/ie.png"),
        Country(name: "Israel", code: "IL", flagPath: "assets/flags/il.png"),
        Country(name: "Italy", code: "IT", flagPath: "assets/flags/it.png"),
        Country(name: "Jamaica", code: "JM", flagPath: "assets/flags/jm.png"),
        Country(name: "Japan", code: "JP", flagPath: "assets/flags/jp.png"),
        Country(name: "Jordan", code: "JO", flagPath: "assets/flags/jo.png"),
        Country(
            name: "Kazakhstan", code: "KZ", flagPath: "assets/flags/kz.png"),
        Country(name: "Kenya", code: "KE", flagPath: "assets/flags/ke.png"),
        Country(name: "Kiribati", code: "KI", flagPath: "assets/flags/ki.png"),
        Country(
            name: "Korea, North", code: "KP", flagPath: "assets/flags/kp.png"),
        Country(
            name: "Korea, South", code: "KR", flagPath: "assets/flags/kr.png"),
        Country(name: "Kosovo", code: "XK", flagPath: "assets/flags/xk.png"),
        Country(name: "Kuwait", code: "KW", flagPath: "assets/flags/kw.png"),
        Country(
            name: "Kyrgyzstan", code: "KG", flagPath: "assets/flags/kg.png"),
        Country(name: "Laos", code: "LA", flagPath: "assets/flags/la.png"),
        Country(name: "Latvia", code: "LV", flagPath: "assets/flags/lv.png"),
        Country(name: "Lebanon", code: "LB", flagPath: "assets/flags/lb.png"),
        Country(name: "Lesotho", code: "LS", flagPath: "assets/flags/ls.png"),
        Country(name: "Liberia", code: "LR", flagPath: "assets/flags/lr.png"),
        Country(name: "Libya", code: "LY", flagPath: "assets/flags/ly.png"),
        Country(
            name: "Liechtenstein", code: "LI", flagPath: "assets/flags/li.png"),
        Country(name: "Lithuania", code: "LT", flagPath: "assets/flags/lt.png"),
        Country(
            name: "Luxembourg", code: "LU", flagPath: "assets/flags/lu.png"),
        Country(
            name: "Madagascar", code: "MG", flagPath: "assets/flags/mg.png"),
        Country(name: "Malawi", code: "MW", flagPath: "assets/flags/mw.png"),
        Country(name: "Malaysia", code: "MY", flagPath: "assets/flags/my.png"),
        Country(name: "Maldives", code: "MV", flagPath: "assets/flags/mv.png"),
        Country(name: "Mali", code: "ML", flagPath: "assets/flags/ml.png"),
        Country(name: "Malta", code: "MT", flagPath: "assets/flags/mt.png"),
        Country(
            name: "Marshall Islands",
            code: "MH",
            flagPath: "assets/flags/mh.png"),
        Country(
            name: "Mauritania", code: "MR", flagPath: "assets/flags/mr.png"),
        Country(name: "Mauritius", code: "MU", flagPath: "assets/flags/mu.png"),
        Country(name: "Mexico", code: "MX", flagPath: "assets/flags/mx.png"),
        Country(
            name: "Micronesia", code: "FM", flagPath: "assets/flags/fm.png"),
        Country(name: "Moldova", code: "MD", flagPath: "assets/flags/md.png"),
        Country(name: "Monaco", code: "MC", flagPath: "assets/flags/mc.png"),
        Country(name: "Mongolia", code: "MN", flagPath: "assets/flags/mn.png"),
        Country(
            name: "Montenegro", code: "ME", flagPath: "assets/flags/me.png"),
        Country(name: "Morocco", code: "MA", flagPath: "assets/flags/ma.png"),
        Country(
            name: "Mozambique", code: "MZ", flagPath: "assets/flags/mz.png"),
        Country(name: "Myanmar", code: "MM", flagPath: "assets/flags/mm.png"),
        Country(name: "Namibia", code: "NA", flagPath: "assets/flags/na.png"),
        Country(name: "Nauru", code: "NR", flagPath: "assets/flags/nr.png"),
        Country(name: "Nepal", code: "NP", flagPath: "assets/flags/np.png"),
        Country(
            name: "Netherlands", code: "NL", flagPath: "assets/flags/nl.png"),
        Country(
            name: "New Zealand", code: "NZ", flagPath: "assets/flags/nz.png"),
        Country(name: "Nicaragua", code: "NI", flagPath: "assets/flags/ni.png"),
        Country(name: "Niger", code: "NE", flagPath: "assets/flags/ne.png"),
        Country(name: "Nigeria", code: "NG", flagPath: "assets/flags/ng.png"),
        Country(
            name: "North Macedonia",
            code: "MK",
            flagPath: "assets/flags/mk.png"),
        Country(name: "Norway", code: "NO", flagPath: "assets/flags/no.png"),
        Country(name: "Oman", code: "OM", flagPath: "assets/flags/om.png"),
        Country(name: "Pakistan", code: "PK", flagPath: "assets/flags/pk.png"),
        Country(name: "Palau", code: "PW", flagPath: "assets/flags/pw.png"),
        Country(name: "Panama", code: "PA", flagPath: "assets/flags/pa.png"),
        Country(
            name: "Papua New Guinea",
            code: "PG",
            flagPath: "assets/flags/pg.png"),
        Country(name: "Paraguay", code: "PY", flagPath: "assets/flags/py.png"),
        Country(name: "Peru", code: "PE", flagPath: "assets/flags/pe.png"),
        Country(
            name: "Philippines", code: "PH", flagPath: "assets/flags/ph.png"),
        Country(name: "Poland", code: "PL", flagPath: "assets/flags/pl.png"),
        Country(name: "Portugal", code: "PT", flagPath: "assets/flags/pt.png"),
        Country(name: "Qatar", code: "QA", flagPath: "assets/flags/qa.png"),
        Country(name: "Romania", code: "RO", flagPath: "assets/flags/ro.png"),
        Country(name: "Russia", code: "RU", flagPath: "assets/flags/ru.png"),
        Country(name: "Rwanda", code: "RW", flagPath: "assets/flags/rw.png"),
        Country(
            name: "Saint Kitts and Nevis",
            code: "KN",
            flagPath: "assets/flags/kn.png"),
        Country(
            name: "Saint Lucia", code: "LC", flagPath: "assets/flags/lc.png"),
        Country(
            name: "Saint Vincent and the Grenadines",
            code: "VC",
            flagPath: "assets/flags/vc.png"),
        Country(name: "Samoa", code: "WS", flagPath: "assets/flags/ws.png"),
        Country(
            name: "San Marino", code: "SM", flagPath: "assets/flags/sm.png"),
        Country(
            name: "Sao Tome and Principe",
            code: "ST",
            flagPath: "assets/flags/st.png"),
        Country(
            name: "Saudi Arabia", code: "SA", flagPath: "assets/flags/sa.png"),
        Country(name: "Senegal", code: "SN", flagPath: "assets/flags/sn.png"),
        Country(name: "Serbia", code: "RS", flagPath: "assets/flags/rs.png"),
        Country(
            name: "Seychelles", code: "SC", flagPath: "assets/flags/sc.png"),
        Country(
            name: "Sierra Leone", code: "SL", flagPath: "assets/flags/sl.png"),
        Country(name: "Singapore", code: "SG", flagPath: "assets/flags/sg.png"),
        Country(name: "Slovakia", code: "SK", flagPath: "assets/flags/sk.png"),
        Country(name: "Slovenia", code: "SI", flagPath: "assets/flags/si.png"),
        Country(
            name: "Solomon Islands",
            code: "SB",
            flagPath: "assets/flags/sb.png"),
        Country(name: "Somalia", code: "SO", flagPath: "assets/flags/so.png"),
        Country(
            name: "South Africa", code: "ZA", flagPath: "assets/flags/za.png"),
        Country(
            name: "South Sudan", code: "SS", flagPath: "assets/flags/ss.png"),
        Country(name: "Spain", code: "ES", flagPath: "assets/flags/es.png"),
        Country(name: "Sri Lanka", code: "LK", flagPath: "assets/flags/lk.png"),
        Country(name: "Sudan", code: "SD", flagPath: "assets/flags/sd.png"),
        Country(name: "Suriname", code: "SR", flagPath: "assets/flags/sr.png"),
        Country(name: "Sweden", code: "SE", flagPath: "assets/flags/se.png"),
        Country(
            name: "Switzerland", code: "CH", flagPath: "assets/flags/ch.png"),
        Country(name: "Syria", code: "SY", flagPath: "assets/flags/sy.png"),
        Country(name: "Taiwan", code: "TW", flagPath: "assets/flags/tw.png"),
        Country(
            name: "Tajikistan", code: "TJ", flagPath: "assets/flags/tj.png"),
        Country(name: "Tanzania", code: "TZ", flagPath: "assets/flags/tz.png"),
        Country(name: "Thailand", code: "TH", flagPath: "assets/flags/th.png"),
        Country(name: "Togo", code: "TG", flagPath: "assets/flags/tg.png"),
        Country(name: "Tonga", code: "TO", flagPath: "assets/flags/to.png"),
        Country(
            name: "Trinidad and Tobago",
            code: "TT",
            flagPath: "assets/flags/tt.png"),
        Country(name: "Tunisia", code: "TN", flagPath: "assets/flags/tn.png"),
        Country(name: "Turkey", code: "TR", flagPath: "assets/flags/tr.png"),
        Country(
            name: "Turkmenistan", code: "TM", flagPath: "assets/flags/tm.png"),
        Country(name: "Tuvalu", code: "TV", flagPath: "assets/flags/tv.png"),
        Country(name: "Uganda", code: "UG", flagPath: "assets/flags/ug.png"),
        Country(name: "Ukraine", code: "UA", flagPath: "assets/flags/ua.png"),
        Country(
            name: "United Arab Emirates",
            code: "AE",
            flagPath: "assets/flags/ae.png"),
        Country(
            name: "United Kingdom",
            code: "GB",
            flagPath: "assets/flags/gb.png"),
        Country(
            name: "United States", code: "US", flagPath: "assets/flags/us.png"),
        Country(name: "Uruguay", code: "UY", flagPath: "assets/flags/uy.png"),
        Country(
            name: "Uzbekistan", code: "UZ", flagPath: "assets/flags/uz.png"),
        Country(name: "Vanuatu", code: "VU", flagPath: "assets/flags/vu.png"),
        Country(
            name: "Vatican City", code: "VA", flagPath: "assets/flags/va.png"),
        Country(name: "Venezuela", code: "VE", flagPath: "assets/flags/ve.png"),
        Country(name: "Vietnam", code: "VN", flagPath: "assets/flags/vn.png"),
        Country(name: "Yemen", code: "YE", flagPath: "assets/flags/ye.png"),
        Country(name: "Zambia", code: "ZM", flagPath: "assets/flags/zm.png"),
        Country(name: "Zimbabwe", code: "ZW", flagPath: "assets/flags/zw.png"),
      ];

  static String? getCountryNameByCode(String isoCode) {
    // Busca o país na lista cujo código corresponda ao ISO fornecido
    Country? country = countries.firstWhere(
      (country) => country.code.toUpperCase() == isoCode.toUpperCase(),
      //  orElse: () => null, // Retorna null se nenhum país for encontrado
    );

    // Retorna o nome do país ou null se não for encontrado
    return country?.name;
  }
}

class CountryCodes {
  static Map<String, Map<String, String>> get codes => {
        "Afghanistan": {"code": "AF", "dialCode": "+93"},
        "Albania": {"code": "AL", "dialCode": "+355"},
        "Algeria": {"code": "DZ", "dialCode": "+213"},
        "American Samoa": {"code": "ASM", "dialCode": "+1684"},
        "Andorra": {"code": "AD", "dialCode": "+376"},
        "Angola": {"code": "AO", "dialCode": "+244"},
        "Anquilla": {"code": "AGO", "dialCode": "+1264"},
        "Antartica": {"code": "AQ", "dialCode": "+672"},
        "Antigua and Barbuda": {"code": "AG", "dialCode": "+1268"},
        "Argentina": {"code": "AR", "dialCode": "+54"},
        "Armenia": {"code": "AM", "dialCode": "+374"},
        "Aruba": {"code": "AW", "dialCode": "+297"},
        "Australia": {"code": "AU", "dialCode": "+61"},
        "Austria": {"code": "AT", "dialCode": "+43"},
        "Azerbaijan": {"code": "AZ", "dialCode": "+994"},
        "Bahamas": {"code": "BS", "dialCode": "+1-242"},
        "Bahrain": {"code": "BH", "dialCode": "+973"},
        "Bangladesh": {"code": "BD", "dialCode": "+880"},
        "Barbados": {"code": "BB", "dialCode": "+1-246"},
        "Belarus": {"code": "BY", "dialCode": "+375"},
        "Belgium": {"code": "BE", "dialCode": "+32"},
        "Belize": {"code": "BZ", "dialCode": "+501"},
        "Benin": {"code": "BJ", "dialCode": "+229"},
        "Bermuda": {"code": "BM", "dialCode": "+1441"},
        "Bhutan": {"code": "BT", "dialCode": "+975"},
        "Bolivia": {"code": "BO", "dialCode": "+591"},
        "Bosnia and Herzegovina": {"code": "BA", "dialCode": "+387"},
        "Botswana": {"code": "BW", "dialCode": "+267"},
        "Brazil": {"code": "BR", "dialCode": "+55"},
        "British Indian Ocean Territory": {"code": "IO", "dialCode": "+672"},
        "Brunei": {"code": "BN", "dialCode": "+673"},
        "Bulgaria": {"code": "BG", "dialCode": "+359"},
        "Burkina Faso": {"code": "BF", "dialCode": "+226"},
        "Burundi": {"code": "BI", "dialCode": "+257"},
        "Cambodia": {"code": "KH", "dialCode": "+855"},
        "Cameroon": {"code": "CM", "dialCode": "+237"},
        "Canada": {"code": "CA", "dialCode": "+1"},
        "Cape Verde": {"code": "CV", "dialCode": "+238"},
        "Cayman Islands": {"code": "KY", "dialCode": "+1345"},
        "Central African Republic": {"code": "CF", "dialCode": "+236"},
        "Chad": {"code": "TD", "dialCode": "+235"},
        "Chile": {"code": "CL", "dialCode": "+56"},
        "China": {"code": "CN", "dialCode": "+86"},
        "Colombia": {"code": "CO", "dialCode": "+57"},
        "Comoros": {"code": "KM", "dialCode": "+269"},
        "Congo Republic of the": {"code": "CG", "dialCode": "+242"},
        "Congo Democratic Republic of the": {"code": "CD", "dialCode": "+243"},
        "Cook Islands": {"code": "CK", "dialCode": "+682"},
        "Costa Rica": {"code": "CR", "dialCode": "+506"},
        "Côte d'Ivoire": {"code": "CIV", "dialCode": "+225"},
        "Croatia": {"code": "HR", "dialCode": "+385"},
        "Cuba": {"code": "CU", "dialCode": "+53"},
        "Cyprus": {"code": "CY", "dialCode": "+357"},
        "Czech Republic": {"code": "CZ", "dialCode": "+420"},
        "Denmark": {"code": "DK", "dialCode": "+45"},
        "Djibouti": {"code": "DJ", "dialCode": "+253"},
        "Dominica": {"code": "DM", "dialCode": "+1-767"},
        "Dominican Republic": {"code": "DO", "dialCode": "+1"},
        "Ecuador": {"code": "EC", "dialCode": "+593"},
        "Egypt": {"code": "EG", "dialCode": "+20"},
        "El Salvador": {"code": "SV", "dialCode": "+503"},
        "Equatorial Guinea": {"code": "GQ", "dialCode": "+240"},
        "Eritrea": {"code": "ER", "dialCode": "+291"},
        "Estonia": {"code": "EE", "dialCode": "+372"},
        "Eswatini": {"code": "SZ", "dialCode": "+268"},
        "Ethiopia": {"code": "ET", "dialCode": "+251"},
        "Falkland Islands (Malvinas)": {"code": "FLK", "dialCode": "+500"},
        "Faroe Islands": {"code": "FRO", "dialCode": "+298"},
        "Fiji": {"code": "FJ", "dialCode": "+679"},
        "Finland": {"code": "FI", "dialCode": "+358"},
        "France": {"code": "FR", "dialCode": "+33"},
        "French Guiana": {"code": "GF", "dialCode": "+594"},
        "French Polynesia": {"code": "PF", "dialCode": "+689"},
        "French Southern Territories": {"code": "TF", "dialCode": "+262"},
        "Gabon": {"code": "GA", "dialCode": "+241"},
        "Gambia": {"code": "GM", "dialCode": "+220"},
        "Georgia": {"code": "GE", "dialCode": "+995"},
        "Germany": {"code": "DE", "dialCode": "+49"},
        "Ghana": {"code": "GH", "dialCode": "+233"},
        "Gibraltar": {"code": "GI", "dialCode": "+350"},
        "Greece": {"code": "GR", "dialCode": "+30"},
        "Greenland": {"code": "GL", "dialCode": "+299"},
        "Grenada": {"code": "GD", "dialCode": "+1473"},
        "Guadeloupe": {"code": "GP", "dialCode": "+590"},
        "Guam": {"code": "GUM", "dialCode": "+1671"},
        "Guatemala": {"code": "GT", "dialCode": "+502"},
        "Guinea": {"code": "GN", "dialCode": "+224"},
        "Guinea-Bissau": {"code": "GW", "dialCode": "+245"},
        "Guyana": {"code": "GY", "dialCode": "+592"},
        "Haiti": {"code": "HT", "dialCode": "+509"},
        "Honduras": {"code": "HN", "dialCode": "+504"},
        //aqui
        "Hungary": {"code": "HU", "dialCode": "+36"},
        "Iceland": {"code": "IS", "dialCode": "+354"},
        "India": {"code": "IN", "dialCode": "+91"},
        "Indonesia": {"code": "ID", "dialCode": "+62"},
        "Iran": {"code": "IR", "dialCode": "+98"},
        "Iraq": {"code": "IQ", "dialCode": "+964"},
        "Ireland": {"code": "IE", "dialCode": "+353"},
        "Israel": {"code": "IL", "dialCode": "+972"},
        "Italy": {"code": "IT", "dialCode": "+39"},
        "Jamaica": {"code": "JM", "dialCode": "+1-876"},
        "Japan": {"code": "JP", "dialCode": "+81"},
        "Jordan": {"code": "JO", "dialCode": "+962"},
        "Kazakhstan": {"code": "KZ", "dialCode": "+7"},
        "Kenya": {"code": "KE", "dialCode": "+254"},
        "Kiribati": {"code": "KI", "dialCode": "+686"},
        "Kuwait": {"code": "KW", "dialCode": "+965"},
        "Kyrgyzstan": {"code": "KG", "dialCode": "+996"},
        "Laos": {"code": "LA", "dialCode": "+856"},
        "Latvia": {"code": "LV", "dialCode": "+371"},
        "Lebanon": {"code": "LB", "dialCode": "+961"},
        "Lesotho": {"code": "LS", "dialCode": "+266"},
        "Liberia": {"code": "LR", "dialCode": "+231"},
        "Libya": {"code": "LY", "dialCode": "+218"},
        "Liechtenstein": {"code": "LI", "dialCode": "+423"},
        "Lithuania": {"code": "LT", "dialCode": "+370"},
        "Luxembourg": {"code": "LU", "dialCode": "+352"},
        "Madagascar": {"code": "MG", "dialCode": "+261"},
        "Malawi": {"code": "MW", "dialCode": "+265"},
        "Malaysia": {"code": "MY", "dialCode": "+60"},
        "Maldives": {"code": "MV", "dialCode": "+960"},
        "Mali": {"code": "ML", "dialCode": "+223"},
        "Malta": {"code": "MT", "dialCode": "+356"},
        "Marshall Islands": {"code": "MH", "dialCode": "+692"},
        "Mauritania": {"code": "MR", "dialCode": "+222"},
        "Mauritius": {"code": "MU", "dialCode": "+230"},
        "Mexico": {"code": "MX", "dialCode": "+52"},
        "Micronesia": {"code": "FM", "dialCode": "+691"},
        "Moldova": {"code": "MD", "dialCode": "+373"},
        "Monaco": {"code": "MC", "dialCode": "+377"},
        "Mongolia": {"code": "MN", "dialCode": "+976"},
        "Montenegro": {"code": "ME", "dialCode": "+382"},
        "Morocco": {"code": "MA", "dialCode": "+212"},
        "Mozambique": {"code": "MZ", "dialCode": "+258"},
        "Myanmar": {"code": "MM", "dialCode": "+95"},
        "Namibia": {"code": "NA", "dialCode": "+264"},
        "Nauru": {"code": "NR", "dialCode": "+674"},
        "Nepal": {"code": "NP", "dialCode": "+977"},
        "Netherlands": {"code": "NL", "dialCode": "+31"},
        "New Zealand": {"code": "NZ", "dialCode": "+64"},
        "Nicaragua": {"code": "NI", "dialCode": "+505"},
        "Niger": {"code": "NE", "dialCode": "+227"},
        "Nigeria": {"code": "NG", "dialCode": "+234"},
        "North Macedonia": {"code": "MK", "dialCode": "+389"},
        "Norway": {"code": "NO", "dialCode": "+47"},
        "Oman": {"code": "OM", "dialCode": "+968"},
        "Pakistan": {"code": "PK", "dialCode": "+92"},
        "Palau": {"code": "PW", "dialCode": "+680"},
        "Panama": {"code": "PA", "dialCode": "+507"},
        "Papua New Guinea": {"code": "PG", "dialCode": "+675"},
        "Paraguay": {"code": "PY", "dialCode": "+595"},
        "Peru": {"code": "PE", "dialCode": "+51"},
        "Philippines": {"code": "PH", "dialCode": "+63"},
        "Poland": {"code": "PL", "dialCode": "+48"},
        "Portugal": {"code": "PT", "dialCode": "+351"},
        "Qatar": {"code": "QA", "dialCode": "+974"},
        "Romania": {"code": "RO", "dialCode": "+40"},
        "Russia": {"code": "RU", "dialCode": "+7"},
        "Rwanda": {"code": "RW", "dialCode": "+250"},
        "Saint Kitts and Nevis": {"code": "KN", "dialCode": "+1-869"},
        "Saint Lucia": {"code": "LC", "dialCode": "+1-758"},
        "Saint Vincent and the Grenadines": {
          "code": "VC",
          "dialCode": "+1-784"
        },
        "Samoa": {"code": "WS", "dialCode": "+685"},
        "San Marino": {"code": "SM", "dialCode": "+378"},
        "Sao Tome and Principe": {"code": "ST", "dialCode": "+239"},
        "Saudi Arabia": {"code": "SA", "dialCode": "+966"},
        "Senegal": {"code": "SN", "dialCode": "+221"},
        "Serbia": {"code": "RS", "dialCode": "+381"},
        "Seychelles": {"code": "SC", "dialCode": "+248"},
        "Sierra Leone": {"code": "SL", "dialCode": "+232"},
        "Singapore": {"code": "SG", "dialCode": "+65"},
        "Slovakia": {"code": "SK", "dialCode": "+421"},
        "Slovenia": {"code": "SI", "dialCode": "+386"},
        "Solomon Islands": {"code": "SB", "dialCode": "+677"},
        "Somalia": {"code": "SO", "dialCode": "+252"},
        "South Africa": {"code": "ZA", "dialCode": "+27"},
        "South Sudan": {"code": "SS", "dialCode": "+211"},
        "Spain": {"code": "ES", "dialCode": "+34"},
        "Sri Lanka": {"code": "LK", "dialCode": "+94"},
        "Sudan": {"code": "SD", "dialCode": "+249"},
        "Suriname": {"code": "SR", "dialCode": "+597"},
        "Sweden": {"code": "SE", "dialCode": "+46"},
        "Switzerland": {"code": "CH", "dialCode": "+41"},
        "Syria": {"code": "SY", "dialCode": "+963"},
        "Taiwan": {"code": "TW", "dialCode": "+886"},
        "Tajikistan": {"code": "TJ", "dialCode": "+992"},
        "Tanzania": {"code": "TZ", "dialCode": "+255"},
        "Thailand": {"code": "TH", "dialCode": "+66"},
        "Togo": {"code": "TG", "dialCode": "+228"},
        "Tonga": {"code": "TO", "dialCode": "+676"},
        "Trinidad and Tobago": {"code": "TT", "dialCode": "+1-868"},
        "Tunisia": {"code": "TN", "dialCode": "+216"},
        "Turkey": {"code": "TR", "dialCode": "+90"},
        "Turkmenistan": {"code": "TM", "dialCode": "+993"},
        "Tuvalu": {"code": "TV", "dialCode": "+688"},
        "Uganda": {"code": "UG", "dialCode": "+256"},
        "Ukraine": {"code": "UA", "dialCode": "+380"},
        "United Arab Emirates": {"code": "AE", "dialCode": "+971"},
        "United Kingdom": {"code": "GB", "dialCode": "+44"},
        "United States": {"code": "US", "dialCode": "+1"},
        "Uruguay": {"code": "UY", "dialCode": "+598"},
        "Uzbekistan": {"code": "UZ", "dialCode": "+998"},
        "Vanuatu": {"code": "VU", "dialCode": "+678"},
        "Vatican City": {"code": "VA", "dialCode": "+39"},
        "Venezuela": {"code": "VE", "dialCode": "+58"},
        "Vietnam": {"code": "VN", "dialCode": "+84"},
        "Yemen": {"code": "YE", "dialCode": "+967"},
        "Zambia": {"code": "ZM", "dialCode": "+260"},
        "Zimbabwe": {"code": "ZW", "dialCode": "+263"},
      };

  static Map<String, String>? findCountryByDialCode(String dialCode) {
    for (var entry in codes.entries) {
      if (entry.value['dialCode'] == dialCode) {
        return {"code": entry.key, "code": entry.value['code'] ?? ''};
      }
    }
    return null; // If no matching dial code is found
  }
}
