name: flutter_responsiveteste
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3

  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  responsive_framework: ^1.1.1
  syncfusion_flutter_calendar: ^23.1.42
  syncfusion_localizations: ^23.1.43
  fluent_ui: ^4.8.2
  screensizer: ^0.0.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
