name: help_center_itgdoodo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_vector_icons: ^2.0.0
  intl_phone_number_input: ^0.7.3+1
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^3.0.0
  fl_chart: ^0.66.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
